personalProject/functionalStrat/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('strat/<int:strat_id>/update_project', views.updateStrat, name='update-strat'),
    path('strat/<int:strat_id>/delete_strat', views.deleteStrat, name='delete-strat'),
    path('boss/<int:boss_id>/add_strat', views.createStrat, name='create-strat'),
    path('boss/<int:pk>', views.BossDetailView.as_view(), name='boss-detail'),
    path('strat/<int:pk>', views.BossStratDetailView.as_view(), name='strat-detail'),
    path('expansion/<int:pk>',views.ExpansionDetailView.as_view(), name='expansion-detail'),
    path('raid/<int:pk>',views.RaidDetailView.as_view(),name='raid-detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.registerPage, name = 'register_page'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

personalProject/personal_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('functionalStrat.urls')),
    
]

personalProject/functionalStrat/models.py
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User


class Expansion(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("expansion-detail", args=[str(self.id)])
    
    def get_raid(self):
        return Raid.objects.select_related('expansion').all().filter(expansion=self.id)
    
class Raid(models.Model):
    name = models.CharField(max_length=200)
    expansion = models.ForeignKey(Expansion, null=True, on_delete=models.CASCADE, blank=True)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("raid-detail", args=[str(self.id)])
    
    def get_bosses(self):
        return Boss.objects.select_related('raid').all().filter(raid=self.id)
    
# Create your models here.
class Boss(models.Model):
    name = models.CharField(max_length = 200)
    raid = models.ForeignKey(Raid, null=True, on_delete=models.CASCADE, blank=True)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("boss-detail", args=[str(self.id)])

class BossStrat(models.Model):
    title = models.CharField(max_length = 200, default='Boss Name Here')
    description = models.CharField(max_length=1000,default='Boss Description Here')
    is_active = models.BooleanField(default=True,)
    roster = models.TextField(blank=True)
    ertNote = models.TextField(blank=True)
    weakaura = models.CharField(max_length=200,blank=True)
    video = EmbedVideoField(blank=True)
    boss = models.ForeignKey(Boss, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("strat-detail", args=[str(self.id)])
    

class RaidAssist(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

class RaidLeader(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

class RaidMember(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

personalProject/functionalStrat/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class StratForm(ModelForm):
    class Meta:
        model = BossStrat
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

personalProject/functionalStrat/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView,DetailView
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users

# Create your views here.

def index(request):
    expansions = Expansion.objects.all()
    return render(request, 'functionalStrat/index.html', {'expansions':expansions})

def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='raid_member')
            user.groups.add(group)
            member = RaidMember.objects.create(user=user,)
            member.save()

            messages.success(request, 'Account was created for ' + username)
            return redirect('login')

    context ={'form':form}
    return render(request, 'registration/register.html', context)


class BossStratDetailView(DetailView):
    model = BossStrat

class BossStratListView(ListView):
    model = BossStrat

class ExpansionListView(ListView):
    model = Expansion

class ExpansionDetailView(DetailView):
    model = Expansion

class RaidListView(ListView):
    model = Raid

class BossDetailView(DetailView):
    model = Boss

class RaidDetailView(DetailView):
    model = Raid

@login_required(login_url='login')
@allowed_users(allowed_roles=['raid_leader'])
def createStrat(request, boss_id):
    form = StratForm()
    boss = Boss.objects.get(pk=boss_id)
    
    if request.method == 'POST':
        strat_data = request.POST.copy()
        strat_data['boss_id'] = boss_id
        form = StratForm(strat_data)

        if 'Cancel' in request.POST:
            return redirect('boss-detail',boss_id)
        
        elif form.is_valid():
            strat = form.save(commit=False)
            strat.boss = boss
            strat.save()

            return redirect('boss-detail',boss_id)
    context = {'form': form}
    return render(request, 'functionalStrat/update_create_form.html', context)    

@login_required(login_url='login')
@allowed_users(allowed_roles=['raid_leader', 'raid_assistant'])
def updateStrat(request, strat_id):
    strat = BossStrat.objects.get(pk=strat_id)
    form = StratForm(instance=strat)

    if request.method == 'POST':
        form = StratForm(request.POST, instance=strat)

        if 'Cancel' in request.POST:
            return redirect('boss-detail', strat.boss.pk)
        
        elif form.is_valid():
            form.save()
            return redirect('strat-detail', strat_id)
        
    context = {'form': form}
    return render(request, 'functionalStrat/update_create_form.html', context)
@login_required(login_url='login')
@allowed_users(allowed_roles=['raid_leader'])
def deleteStrat(request, strat_id):
    strat = BossStrat.objects.get(pk=strat_id)

    if request.method == 'POST':

        if 'Cancel' in request.POST:
            return redirect('boss-detail', strat.boss.pk)
        
        else:
            strat.delete()
            return redirect('boss-detail', strat.boss.pk)
    
    return render(request,'functionalStrat/delete_form.html', {'strat': strat})

personalProject/functionalStrat/templates/functionalStrat/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
   <title>UCCS CS Students</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Bootstrap demo</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   {% load django_bootstrap5 %}
   {% bootstrap_css %}
   {% bootstrap_messages %}
  </head>

 <body style="background-color:#f7feff">
   <div class="container-fluid" text-warning bg-dark>

     <!-- Navbar-->
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-clip:content-box;box-shadow: inset 0 0 0 10px #FFF7FE;">
       <img src="{% static 'images/functional.jpg' %}" width="200" height="100">

       <div class="container-fluid" >
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

           <div class="navbar-nav">
             <!--  {% url 'index' %}  is defined in url path to dynamically create url -->
             <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}?next={{request.path }}">LOGOUT {{user}}</a>
            {% else %}
             <a class="nav-link" href="{% url 'login' %}?next={{request.path }}">LOGIN</a>
            {%endif%}
           </div> <!-- Navbar -->

         </div> <!-- collapse navbar -->

       </div> <!-- container -->

     </nav>

       <div class="col-sm-10">
         <!-- add block content from html template -->
         {% block content %}
         {% endblock %}
       </div>
     </div>
   </div>
 </body>
</html>

personalProject/functionalStrat/templates/functionalStrat/boss_detail.html
{% extends "functionalStrat/base_template.html" %}

{% block content %}

<h1 style="font-size:32px">Boss: {{boss.name}} </h1>

<h2><strong>Strategies</strong><a href="{%url 'create-strat' boss_id=boss.pk %}" class="btn btn-dark">Add a Strategy</a></h2>
<ul class="list-group">
    {% for strategy in boss.bossstrat_set.all %}
        <li style="font-size:20px;background-color:#FEFFF7" class="list-group-item"> Title: {{strategy.title}} <p></p> 
            <a href="{{strategy.get_absolute_url}}" class="btn btn-dark">View</a>
            <a href="{%url 'update-strat' strat_id=strategy.pk %}" class="btn btn-dark">Update Strategy</a>
            <a href="{%url 'delete-strat' strat_id=strategy.pk %}" class="btn btn-dark">Delete Strategy</a>
        </li>
    {%endfor%}
</ul>

{% endblock %}

personalProject/functionalStrat/templates/functionalStrat/bossstrat_detail.html
{% extends "functionalStrat/base_template.html" %}

{% load embed_video_tags %}
{% block content %}

<h1 style="font-size:32px"> Strategy Title: {{bossstrat.title}}

</h1>

<p></p>

{%if bossstrat.description%} 
<p style="font-size:20px"> About: {{bossstrat.description}} </p> 
{%endif%}

{%if bossstrat.roster%} 
<p style="font-size:20px"> Roster: {{bossstrat.roster}} </p>
{%endif%}

{%if bossstrat.video%}
<p>    {% video bossstrat.video 'small' %} </p>
{%endif%}

{%if bossstrat.ertNote%}
<p> ERT Note </p>
<li> {{bossstrat.ertNote}} </li>
<p></p>
{%endif%}

{%if bossstrat.weakaura%}
    <a href="{{bossstrat.weakaura}}" class="btn btn-dark">View Weakaura </a>
{%endif%}
{%endblock%}

personalProject/functionalStrat/templates/functionalStrat/delete_form.html
{% extends "functionalStrat/base_template.html" %}

{%block content%}

<!-- Give user information-->
<h1> Delete Strategy </h1>
<p style="font-size:24px"> Are you sure you want to delete the project: {{strat.title}} </;p>

<!-- Perform action -->
<form action="" method="POST">
    
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" class="btn btn-primary" name="Submit">
    <input type="submit" class="btn btn-danger" value="Cancel" name="Cancel">

</form>

{%endblock%}

personalProject/functionalStrat/templates/functionalStrat/expansion_detail.html
{% extends "functionalStrat/base_template.html" %}

{% block content %}

<h1 style="font-size:32px"> Expansion: {{expansion.name}}

</h1>

<p></p>

{%for raid in expansion.get_raid %}
    <li class="list-group-item text-info bg-dark"> Raid: <strong class="text-Success"> {{raid.name}}</strong>
        <a href="{{raid.get_absolute_url}}" class="btn btn-warning">Bosses </a>
    </li>
{%endfor%}

{%endblock%}

personalProject/functionalStrat/templates/functionalStrat/index.html
<!-- inherit from base.html-->
{% extends "functionalStrat/base_template.html" %}

<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Functional Boss Strategies</h1>

<h2> Choose the Expansion </h2>
    <ul class="list-group">
        {% for x in expansions%}
        <li class="list-group-item" text-info bg-dark"><strong class="text-Success">{{ x.name}}</strong>
            <a href="{{x.get_absolute_url}}" class="btn btn-dark">View</a>
        </li>
        {%endfor%}
    </ul>

{% endblock %}

personalProject/functionalStrat/templates/functionalStrat/raid_detail.html
{% extends "functionalStrat/base_template.html" %}

{% block content %}

<h1 style="font-size:32px"> Raid: {{raid.name}}

</h1>

<p></p>

{%for boss in raid.get_bosses %}
    <li class="list-group-item text-info bg-dark"> Raid: <strong class="text-Success"> {{boss.name}}</strong>
       <a href="{{boss.get_absolute_url}}" class="btn btn-warning">Strategies </a>
    </li>
{%endfor%}

{%endblock%}

personalProject/functionalStrat/templates/functionalStrat/update_create_form.html
{% extends "functionalStrat/base_template.html" %}

{% block content %}

<form action="" method="POST">

    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" class="btn btn-primary" name="Submit">
    <input type="submit" class="btn btn-danger" value="Cancel" name="Cancel" formnovalidate>

</form>

{% endblock %}